#!/bin/sh

echo "author: ZR233"
mount -t proc proc /proc
mount -t sysfs sysfs /sys
dmesg -n 8
# ip addr add 10.0.2.15/24 dev eth0
# ip link set dev eth0 up
# ip route add default via 10.0.2.2 dev eth0
